### PR TITLE
Xinyu Zheng Week07 assignment submission

### PR DESCRIPTION
**Pull request by XZXinyuZheng**

### CODE REVIEW

**Review by bnhippolyte — COMMENTED** [review]
Great survey Xinyu ! Questions are very detailed and the intro note gives a clear idea of the survey. Unfortunately I was not able to actually submit information on my energy consumption, the survey ended and I did not get to these questions. I reviewed the google sheet to identify if there was a condition that needs to be satisfied before I could move on to the energy consumption questions but I was not able to identify any condition that was needed. Perhaps you can provide some clarification on this issue and I could review the survey again.

**Comment by XZXinyuZheng** [comment]
Hi BeverlyAnn! Thank you for your comments. I did set a condition that the survey taker has to live in this reported home address for over one year to be able to move on to questions about energy consumption. However, I feel this condition is not reasonable now, thanks to your experience filling out the survey. I have removed the condition, and you should be able to submit the energy consumption answers now.

**Comment by bnhippolyte** [comment]
Great job Xinyu ! Survey questions were very clear, detailed and properly organized so that the respondent understands the purpose of the survey and answers questions as accurately as possible. I understand the importance of asking about energy consumption for each month, perhaps that could be shortened to ask the individual to just state their average annual energy consumption and the average amount their paid for the year in gas. Overall great survey !

**Review by bnhippolyte — APPROVED** [review]

**Comment by BeaLeydier** [comment]
Hi @XZXinyuZheng 

Great job on the survey! Please find below some comments to fine tune/improve it.

- FYI, you can use html tags in label fields for surveycto, if you want to add paragraphs or other fomatting (for example, if you wanted the four modules of your survey to be displayed in a list instead of a single line)
- When asking for a 5-digit number for the zipcode, you should enforce that as a constraint (for example with string-length() function)
- You may want to add constraints to avoid absurd values, for example on the ages, the year the house was built, etc
- The energy module also didn't work for me (I think you may need to re-upload the survey after making changes), but here are some thoughts based on the code of it
     - You should provide options for people who don't have gas. Maybe start with a yes/no question on gas, and make all the gas questions only relevant in case of yes.
     - It may also be helpful to ask people what do they use electricity/gas for in general (ie heat, stove, etc), because that will help you interpret the data
     - You can use groups to combine multiple questions in one screen by using "field-list" in the apperance column of that group, to make the survey flow more natural
     - I would move the months question to right after the date of move in question, so it flows naturally for people (you can still use it as a basis for the repeat group if it's earlier in the survey). You should specify if you are only talking about last year's months, or if you are talking about months on average. It is probably better to only cover last year's months, from an accuracy perspective (they can probably easily get the bill). 

Overall, great job! You coded all features and the survey flows quite nicely and would collect useful data to analyze.

**Pull request merged**
