### PR TITLE
Saloni week7 + week8 work

### PR DESCRIPTION
**Pull request by bhatiasaloni28**

### CODE REVIEW

**Review by bnhippolyte — COMMENTED** [review]
I'm not sure where the changes are

**Comment by bhatiasaloni28** [comment]
Hi Ben, 

I may have accidentally uploaded the week07 - survey CTO assignment and week08 - Part 1 (incomplete) on the same branch 'sb2077-week08. I am not sure what is visible on the branch, but I will ensure that the completed week08 assignment is available for review by tomorrow.

**Comment by bhatiasaloni28** [comment]
Hi @bbdaniels, after uploading a few trials - week08 is available for review. Please note that the output still does not run seamlessly and I have added doubts in the end of my file. I should get there with another try.

**Comment by BeaLeydier** [comment]
Hi @bhatiasaloni28 

Thanks for submitting your survey! Some comments below
- Make it more clear who the survey is for at the top and add screening questions so that only relevant respondents are filling it out (for example, only people from India should fill it out)
- You need to attach the countries-continents dataset to your form if you want the pulling of these data to work in your questions
- For the repeat groups about jobs
    - add the length of the repeat group (number of jobs) inside the repeat_count column for the begin repeat row. This way, the survey will not ask each time if we want to add another group, but instead just loop through the questions n times (n being the number of jobs)
    - inside the repeat group, you should specify in each question what job each question is referring to. You will need the index() function for this
- You can make more use of the relevance conditions. For example, the employment repeat groups shouldn;t be relevant if they aren't employed (unless you want to consider people who are currently unemployed but used to be employed; in which case, you probably want to ask that question first too, so you can screen out of the employment question the people who were never employed, etc)

Great job overall! I love that your survey is tied to your group project and gives you an idea of how you could use survey to generate data you aren't observing otherwise around your project.

I will let Ben comment on the week08 and week09 stuff that is also in this PR and merge it when that's done!

**Review by BeaLeydier — COMMENTED** [review]
Week07 review done

**Comment by bbdaniels** [comment]
@bhatiasaloni28 I assume this is not done since there are no write-ups. Let me know when you are ready to submit!

**Pull request merged**
