### PR TITLE
Week07 cmg340 new 

### PR DESCRIPTION
**Pull request by cmg340**
second attempt to submit!

### CODE REVIEW

**Review by mikegiunti — CHANGES_REQUESTED** [review]
Remove the ! from in front of the brackets or the links wont work

**Comment by mikegiunti** [comment]
The repeat group on the form would be more beneficial if put on the ranking of modes of transportation. Additionally, be aware that the naming of modes of transportation for section "transportation_type" does not actually show the name of the mode of transportation.  Side note: the form bea shared gives us an example of how to do an age calculation without directly asking a person what their age is. Just use the "date" function.

For ranking, refer to this link: [How to create a ranking in SurveyCTO](https://support.surveycto.com/hc/en-us/articles/360000432727-How-to-create-a-ranking-question)

**Comment by mikegiunti** [comment]
To refer to previously answered questions use this link: [Using indexed repeat](https://support.surveycto.com/hc/en-us/articles/218131358-Understanding-indexed-repeat-and-the-structure-of-repeat-group-data)

And this link: [Collecting information from multiple repeats](https://docs.surveycto.com/02-designing-forms/04-sample-forms/10.rosters-multiple-repeat.html)

**Comment by mikegiunti** [comment]
Last thing: it pays off to just make things simpler for yourself. If a question seems hard to code: 

A) Don't spend more than 30 minutes on it 
B) Do it differently 
C) Ask something else that is still relevant.

Good Luck!

**Comment by BeaLeydier** [comment]
Hi @cmg340 

Great work on the survey! We had discussed it in office hours, but there is some more detailed feedback

1. You can replace mode_i by a calculation with count-selected()
2. The choice filtering of options doesn't work (all options remain available) : you need to fill out the "filter" column in the choices tab to make it work
3. When you ask the follow up questions, you should use choice-label() to display the name of the mode of transport instead of the value
4. Use groups with field-list in the appearance column to group questions together in one screen
5. You can use the likert option in the appearence column to make a select_one look like a scale; alternatively you can also use field-list (to groups questions in one screen) and label / list-nolabel options to group multiple questions on the same scale into one table
6. I would replace the text questions at the end by select_multiple questions with an **Other** option

Great job! You attempted a pretty difficult coding design with the ranking concept and implemented it quite well.

**Pull request merged**
