### PR TITLE
Week10-Fan Liu assignment

### PR DESCRIPTION
**Pull request by Fan411525**

### CODE REVIEW

**Comment by bbdaniels** [comment]
Marking as incomplete. There is absolutely no way that the minimum required sample size for anything is "two"! Similarly for the second table in Part 1 -- it is not possible that you are fixing the sample size at two.

In Part 2, you have got this backwards. You do not need two DGPs -- you do not even need two regression models! The question is: Given a single DGP and a single regression model, does the `reg` command's analytical CIs correctly match the distribution of beta estimates it produces over many draws. Go back and re-write -- let me know if the tis not clear what is being asked!

**Comment by Fan411525** [comment]
I embed the strata in the first part, that is, even if the sample size = 2, its obs is actually 2*10*[16,25]=[320,500].
The second part of my second DGP is the fifth step of the problem: Create another DGP in which the random error terms are only determined at the cluster level. It is only used to compare the lack of individual random error in the error term on CI convergence difference.

**Comment by Fan411525** [comment]
> Marking as incomplete. There is absolutely no way that the minimum required sample size for anything is "two"! Similarly for the second table in Part 1 -- it is not possible that you are fixing the sample size at two.
> 
> In Part 2, you have got this backwards. You do not need two DGPs -- you do not even need two regression models! The question is: Given a single DGP and a single regression model, does the `reg` command's analytical CIs correctly match the distribution of beta estimates it produces over many draws. Go back and re-write -- let me know if the tis not clear what is being asked!

I embed the strata in the first part, that is, even if the sample size = 2, its obs is actually 210[16,25]=[320,500].

The second part of my second DGP is the fifth step of the problem: Create another DGP in which the random error terms are only determined at the cluster level. It is only used to compare the lack of individual random error in the error term on CI convergence difference.

**Comment by bbdaniels** [comment]
I fully believe that, and I checked the code to understand this as well -- but your writeup of your solution says:

https://github.com/gui2de/ppol768-spring23/blob/c4cab534cf4d3b8f1bbf02158bc22d00e8848589/Individual%20Assignments/Fan%20Liu/week-10/README.md?plain=1#L14

Similarly, in part two, you write:

https://github.com/gui2de/ppol768-spring23/blob/c4cab534cf4d3b8f1bbf02158bc22d00e8848589/Individual%20Assignments/Fan%20Liu/week-10/README.md?plain=1#L26

This is not the question, or the solution, to that problem. In both cases, you need to correct your outputs and writeup to accurately describe your work and solutions to the posed problems. Thanks for writing back and I'm sure you will do well in revising these!

**Pull request merged**
