### PR TITLE
Wk09 cmg340

### PR DESCRIPTION
**Pull request by cmg340**
my loop is not working to store my betas so putting here for help reference, not submission yet

### CODE REVIEW

**Comment by cmg340** [comment]
Submitting week nine assignment

**Comment by bbdaniels** [comment]
Great work! Do you have Week 10 coming?

**Comment by cmg340** [comment]
I'm working on it - I've committed the code for part one but got stuck calculating confidence intervals in part two. at minimum I will have a readme for part one be EOD.

**Comment by cmg340** [comment]
(understanding today is last day to submit -just crunched  for time. Really appreciate being able to submit things today)

**Pull request merged**
