### PR TITLE
Upload Week 08 Assignment Progress (Parts 1 & 2 UPDATED)

### PR DESCRIPTION
**Pull request by pew36**
I have not yet completed this assignment fully! I have only completed part one of two for the week 08 assignment. Please do not merge this pull request into main just yet. Note from 12:05AM EDT on 2023.03.21.

### CODE REVIEW

**Comment by pew36** [comment]
Updates committed on 4/1/2023.

**Comment by marbruno** [comment]
@pew36 If you can confirm when this is ready for peer review (through commit name or a comment), please let me know! Tnx - Marlyn

**Comment by pew36** [comment]
> 

So sorry Marlyn for the delay!! Please go ahead with the peer review so that it's no longer hanging over your head! I may add some commits after you review, because I still need to find a way to create some sort of comparison chart. And I noticed my histogram links are not working.

**Comment by marbruno** [comment]
No rush at all! Just wanted to see if I should be reviewing now or hold off a bit. I'll hold off until you're done :)

**Pull request merged**
