### PR TITLE
editing bio, experimenting with markdown

### PR DESCRIPTION
**Pull request by cmg340**
not sure if i got the markdown right!

### CODE REVIEW

**Review by dnr36 — CHANGES_REQUESTED** [review]
Hey Maeve! I like the personal details you added like your hobbies and the cool bee info! I tried to see the README in your branch but the pictures and the tables are not showing up. I think the issue with the pics is that they're not png and there needs to be an exclamation point before the picture info. As for the tables, I am not sure because I made my tables using a different strategy: adding | and - to create the cells. 
I will approve the merge once these issues are fixed! Nice to meet you!

**Comment by cmg340** [comment]
Hi Diana! thanks for the feedback and markdown tips! I think the images are coming in now! can you let me know if the table looks right?

**Review by dnr36 — CHANGES_REQUESTED** [review]
Hey Maeve, I am still not seeing the pics but I do see you changed their formats. I am not sure why they're not showing up. As for the tables I used this for help https://stackoverflow.com/questions/39378020/how-to-display-table-in-readme-md-file-in-github not sure if this is the best strategy though.

**Comment by cmg340** [comment]
are the pictures supposed to show in-text in the readme? Asking b/c i see them when i scroll down on the "files changed" tab

**Review by dnr36 — CHANGES_REQUESTED** [review]
I talked to Bea and turns out the problem might be because your readme file is .rmd instead of .md once you fix that it should work

**Comment by cmg340** [comment]
thanks for asking! it looks right to me but hopefully it's showing up for you! thanks again for passing on Bea's advice!

**Review by dnr36 — APPROVED** [review]

**Comment by bbdaniels** [comment]
Hi, @cmg340 this is not completed -- the features do not render correctly in the `README`. In addition, you have not named the folder according to the requirement in the assignment. You should go back and fix these!

@dnr36 -- You should not approve changes until they are confirmed to be working!

Screen Shot

**Pull request merged**
