### PR TITLE
week2 update bio and photos

### PR DESCRIPTION
**Pull request by JLei24**

### CODE REVIEW

**Review by sunjw0827 — APPROVED** [review]
good work, sorry for late approve

**Comment by bbdaniels** [comment]
@JLei24 you need to review and complete the assignment again -- the basic features and images are not rendering properly on the page. Also, you need to use the folder name that is requested in the assignment.

@sunjw0827 -- In the future, do not approve work without reviewing it! It is very clear here that updates are necessary for this assignment to be complete, and it is your assignment as a reviewer to provide the necessary constructive feedback for the submitter. Thanks!

Screen Shot

**Comment by JLei24** [comment]
> @JLei24 you need to review and complete the assignment again -- the basic features and images are not rendering properly on the page. Also, you need to use the folder name that is requested in the assignment.
> 
> @sunjw0827 -- In the future, do not approve work without reviewing it! It is very clear here that updates are necessary for this assignment to be complete, and it is your assignment as a reviewer to provide the necessary constructive feedback for the submitter. Thanks!
> 
> Screen Shot


Hello Mr.Daniels 

Thank you for the feedback! For the photos, the link I wrote is profile photo/city phote and the two photos are in the form of png. I am not sure which part is the problem to make it not show properly. 

For the table, I could not find the correct syntax in the manual so what I did was searching "table for markdown syntax" on google and used the format |Title|Author| then next line |------|---|. But it is also messed up. I am just wondering what would be the correct format for table. 


Thank you!

**Comment by bbdaniels** [comment]
You should review the assignments as completed by the other students and troubleshoot in order to get it working for your own materials. We have made sure everyone's working materials are public on this site so that you can learn from each other this way! Please check the materials of someone else who has got it working and you should be able to adapt into your own work here, such as from the person whose work you reviewed. If you still cannot get it working, feel free to come to the drop in hours or book an office hour per the syllabus instructions. All the best!

**Pull request merged**
